#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Thing+ Help

# Short bio or description (displayed in the header)
description:

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/2654927?v=3&u=3b33aa510ecf77453aaffaf1390bd3bd5ee03ced&s=140

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: contact@thingplus.net
  facebook: #daliworks
  flickr:
  github: #daliworks
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: #daliworks
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: #channel/UCa7T7hj3F0x7brM6htUasyQ

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-52262016-5

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.daliworks.net

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
redcarpet:
  extensions: [footnotes]
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
#gems:
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# Set default env for multilingual without plugin
defaults:
  -
    scope:
      path: ""
    values:
      lang: ko
      layout: default
  -
    scope:
      path: _posts/en
    values:
      lang: en
  -
    scope:
      path: _posts/ko/pages
    values:
      type: pages
  -
    scope:
      path: _posts/en/pages
    values:
      type: pages

